In [1]:
import torch
import torchvision
import torch.nn as nn
import numpy as np
import torch.utils.data as data
import torchvision.transforms as transforms
import torchvision.datasets as dsets
from torch.autograd import Variable

##  Basic autograd example 1

In [8]:
# Create tensors.
x = torch.tensor([1], dtype=torch.float32, requires_grad=True)
w = torch.tensor([2], dtype=torch.float32, requires_grad=True)
b = Variable(torch.Tensor([3]), requires_grad=True)

# Build a computational graph.
y = w * x + b  # y = 2 * x + 3

# Compute gradients.
y.backward()

# Print out the gradients.
print(x.grad)  # x.grad = 2
print(w.grad)  # w.grad = 1
print(b.grad)  # b.grad = 1

tensor([ 2.])
tensor([ 1.])
tensor([ 1.])


##  Basic autograd example 2

In [12]:
# Create tensors.
x = Variable(torch.randn(5, 3))
y = Variable(torch.randn(5, 2))

# Build a linear layer.
linear = nn.Linear(3, 2)
print('w: ', linear.weight)
print('b: ', linear.bias)

w:  Parameter containing:
tensor([[ 0.2911, -0.2927, -0.2906],
        [-0.5541,  0.3784,  0.3746]])
b:  Parameter containing:
tensor([ 0.2662,  0.3458])


In [13]:
for p in linear.parameters():
    print(p.shape)

torch.Size([2, 3])
torch.Size([2])


In [15]:
# Build Loss and Optimizer.
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)

# Forward propagation.
pred = linear(x)
print(pred.shape, y.shape)

torch.Size([5, 2]) torch.Size([5, 2])


In [20]:
# Compute loss.
loss = criterion(pred, y)
print('loss: ', loss.item())

loss:  1.252275824546814


In [16]:
# Backpropagation.
loss.backward()

# Print out the gradients.
print('dL/dw: ', linear.weight.grad)
print('dL/db: ', linear.bias.grad)

dL/dw:  tensor([[ 0.1941, -0.5061, -0.3969],
        [ 0.4256,  1.5922,  0.9655]])
dL/db:  tensor([ 0.4807,  0.1702])


In [17]:
# 1-step Optimization (gradient descent).
optimizer.step()

In [19]:
# You can also do optimization at the low level as shown below.
# linear.weight.data.sub_(0.01 * linear.weight.grad.data)
# linear.bias.data.sub_(0.01 * linear.bias.grad.data)

# Print out the loss after optimization.
pred = linear(x)
loss = criterion(pred, y)
print('loss after 1 step optimization: ', loss.item())

loss after 1 step optimization:  1.252275824546814


## Loading data from numpy

In [24]:
a = np.array([[1, 2], [3, 4]])
b = torch.from_numpy(a)  # convert numpy array to torch tensor
b1 = torch.tensor(a)
c = b.numpy()  # convert torch tensor to numpy array
b, b1, c

(tensor([[ 1,  2],
         [ 3,  4]]), tensor([[ 1,  2],
         [ 3,  4]]), array([[1, 2],
        [3, 4]]))

##  Implementing the input pipline

In [ ]:
# Download and construct dataset.
train_dataset = dsets.CIFAR10(
    root='../data/',
    train=True,
    transform=transforms.ToTensor(),
    download=True)

# Select one data pair (read data from disk).
image, label = train_dataset[0]
print(image.size())
print(label)

# Data Loader (this provides queue and thread in a very simple way).
train_loader = torch.utils.data.DataLoader(
    dataset=train_dataset, batch_size=100, shuffle=True, num_workers=2)

# When iteration starts, queue and thread start to load dataset from files.
data_iter = iter(train_loader)

# Mini-batch images and labels.
images, labels = data_iter.next()

# Actual usage of data loader is as below.
for images, labels in train_loader:
    # Your training code will be written here
    pass

##  Input pipline for custom dataset

In [ ]:
# You should build custom dataset as below.
class CustomDataset(data.Dataset):
    def __init__(self):
        # TODO
        # 1. Initialize file path or list of file names.
        pass

    def __getitem__(self, index):
        # TODO
        # 1. Read one data from file (e.g. using numpy.fromfile, PIL.Image.open).
        # 2. Preprocess the data (e.g. torchvision.Transform).
        # 3. Return a data pair (e.g. image and label).
        pass

    def __len__(self):
        # You should change 0 to the total size of your dataset.
        return 0

In [ ]:
# Then, you can just use prebuilt torch's data loader.
custom_dataset = CustomDataset()
train_loader = torch.utils.data.DataLoader(
    dataset=custom_dataset, batch_size=100, shuffle=True, num_workers=2)

##  Using pretrained model

In [ ]:
# Download and load pretrained resnet.
resnet = torchvision.models.resnet18(pretrained=True)

# If you want to finetune only top layer of the model.
for param in resnet.parameters():
    param.requires_grad = False

# Replace top layer for finetuning.
resnet.fc = nn.Linear(resnet.fc.in_features, 100)  # 100 is for example.

# For test.
images = Variable(torch.randn(10, 3, 224, 224))
outputs = resnet(images)
print(outputs.size())  # (10, 100)

##  Save and load the model

In [ ]:
# Save and load the entire model.
torch.save(resnet, 'model.pkl')
model = torch.load('model.pkl')

In [ ]:
# Save and load only the model parameters(recommended).
torch.save(resnet.state_dict(), 'params.pkl')
resnet.load_state_dict(torch.load('params.pkl'))